/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.programminglearningsystem.view;
import com.mycompany.programminglearningsystem.dao.UserDAO;
import com.mycompany.programminglearningsystem.model.User;
import com.mycompany.programminglearningsystem.view.ViewProfileFrame;
import com.mycompany.programminglearningsystem.view.TeamFormationFrame;
import com.mycompany.programminglearningsystem.view.LoginFrame;
import com.mycompany.programminglearningsystem.view.UpdateProfileFrame;
import com.mycompany.programminglearningsystem.session.Session;
public class DashboardFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DashboardFrame.class.getName());

    /**
     * Creates new form DashboardFrame
     */
  public DashboardFrame() {
    initComponents();

    setLocationRelativeTo(null);

    UserDAO dao =
            new UserDAO();

    User user =
            dao.getUserByEmail(
                    Session.currentUserEmail);

    if(user != null){

        lblWelcome.setText(
                "Welcome, "
                + user.getUsername());
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnViewProfile = new javax.swing.JButton();
        btnTeamFormation = new javax.swing.JButton();
        btnUpdateProfile = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblWelcome = new javax.swing.JLabel();
        btnViewProgress = new javax.swing.JButton();
        btnViewCompletion = new javax.swing.JButton();
        btnCourseRegistration = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnViewProfile.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnViewProfile.setText("View Profile");
        btnViewProfile.addActionListener(this::btnViewProfileActionPerformed);

        btnTeamFormation.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnTeamFormation.setText("Team Formation");
        btnTeamFormation.addActionListener(this::btnTeamFormationActionPerformed);

        btnUpdateProfile.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnUpdateProfile.setText("Update Profile");
        btnUpdateProfile.addActionListener(this::btnUpdateProfileActionPerformed);

        btnLogout.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.addActionListener(this::btnLogoutActionPerformed);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel1.setText("PROGRAMMING LEARNING SYSTEM");

        lblWelcome.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblWelcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWelcome.setText("Welcome");
        lblWelcome.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnViewProgress.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnViewProgress.setText("View Progress");
        btnViewProgress.addActionListener(this::btnViewProgressActionPerformed);

        btnViewCompletion.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnViewCompletion.setText("View Completion Status");
        btnViewCompletion.addActionListener(this::btnViewCompletionActionPerformed);

        btnCourseRegistration.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnCourseRegistration.setText("Course Registration");
        btnCourseRegistration.addActionListener(this::btnCourseRegistrationActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnViewProgress, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnUpdateProfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnTeamFormation, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                        .addComponent(btnViewProfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnViewCompletion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCourseRegistration, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addComponent(lblWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(122, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(lblWelcome)
                .addGap(31, 31, 31)
                .addComponent(btnUpdateProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnViewProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnTeamFormation, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCourseRegistration, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnViewProgress, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnViewCompletion, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewProfileActionPerformed


   ViewProfileFrame profile =
        new ViewProfileFrame();

profile.setVisible(true);

this.dispose();
    }//GEN-LAST:event_btnViewProfileActionPerformed

    private void btnTeamFormationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTeamFormationActionPerformed


   TeamFormationFrame team =
        new TeamFormationFrame();

team.setVisible(true);

this.dispose();
    }//GEN-LAST:event_btnTeamFormationActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
 LoginFrame login =
        new LoginFrame();

login.setVisible(true);

this.dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnUpdateProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateProfileActionPerformed
   UpdateProfileFrame update =
        new UpdateProfileFrame();

update.setVisible(true);

this.dispose();
    }//GEN-LAST:event_btnUpdateProfileActionPerformed

    private void btnViewProgressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewProgressActionPerformed


  ViewCompletionStatusFrame frame =
            new ViewCompletionStatusFrame();

    frame.setVisible(true);

    this.dispose();

    }//GEN-LAST:event_btnViewProgressActionPerformed

    private void btnViewCompletionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewCompletionActionPerformed
   ViewProgressFrame frame =
            new ViewProgressFrame();

    frame.setVisible(true);

    this.dispose();
    }//GEN-LAST:event_btnViewCompletionActionPerformed

    private void btnCourseRegistrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCourseRegistrationActionPerformed
    CourseRegistrationFrame frame =
            new CourseRegistrationFrame();

    frame.setVisible(true);

    this.dispose();
    }//GEN-LAST:event_btnCourseRegistrationActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DashboardFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCourseRegistration;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnTeamFormation;
    private javax.swing.JButton btnUpdateProfile;
    private javax.swing.JButton btnViewCompletion;
    private javax.swing.JButton btnViewProfile;
    private javax.swing.JButton btnViewProgress;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblWelcome;
    // End of variables declaration//GEN-END:variables
}
